import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ButtomNavBar from "@/components/navigation/buttomNavBar";
import SideNavBar from "@/components/navigation/sideNavBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const sfPro = localFont({
  src: './fonts/SF-Pro.ttf',
  variable: '--font-sfpro',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "MellowDi - Music streaming web app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="myLight">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sfPro.variable} antialiased bg-secondary-light dark:bg-secondary-dark font-sans`}
      >
          <SideNavBar />
          {children}
          <ButtomNavBar />
      </body>
    </html>
  );
}
